### ISSUE TITLE
算法

### ISSUE THREAD

**Issue by Tomaolala** [Tomaolala/front_end_learn#3]
https://leetcode.cn/studyplan/30-days-of-javascript/

@SONG-GF

这个1周刷完吧，对前端基础还是有点收益的

**Comment by Tomaolala** [comment]
@vegetalbirddd

**Comment by vegetalbirddd** [comment]
干嘛

**Comment by vegetalbirddd** [comment]
没事别艾特我

**Comment by Tomaolala** [comment]
有什么收获在根目录新建自己的文件夹
 /gf
/zyq
这样的

**Comment by Tomaolala** [comment]
> 没事别艾特我

就要

**Comment by SONG-GF** [comment]
好哒





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月3日(星期一) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tomaolala/front_end_learn] 算法 (Issue #3)





 
有什么收获在根目录新建自己的文件夹
 /gf
 /zyq
 这样的
